name: Test

on:
  push:
    branches: [ "develop","main" ]
  workflow_dispatch:
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10.8"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          export PYTHONPATH=$PYTHONPATH:scripts
          chmod +x run_tests.sh
          ./run_tests.sh
        shell: bash